=== saulocalixto/mf-2018/aula-7/dto/src/test/resources/jsonSchema/dadoDemograficoSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "individuo": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    },
    "datadeNascimento": {
      "type": "string"
    },
    "nascimentoAcuracia": {
      "type": "string"
    },
    "nascimentoSegmento": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "string"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "descricao"
      ]
    },
    "nascimentoPluralidade": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "descricao"
      ]
    },
    "nascimentoOrdem": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "descricao"
      ]
    },
    "obito": {
      "type": "string"
    },
    "obitoAcuracia": {
      "type": "string"
    },
    "obitoFonte": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "descricao"
      ]
    },
    "sexo": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "alternativo": {
          "type": "string"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "alternativo",
        "descricao"
      ]
    },
    "mae": {
      "type": "string"
    },
    "pai": {
      "type": "string"
    },
    "situacaoFamiliar": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "descricao"
      ]
    },
    "raca": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "descricao"
      ]
    },
    "comentario": {
      "type": "string"
    },
    "nacionalidade": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "descricao": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "descricao"
      ]
    },
    "municipio": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "string"
        },
        "estado": {
          "type": "string"
        },
        "municipio": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "estado",
        "municipio"
      ]
    },
    "estado": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "string"
        },
        "nome": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "nome"
      ]
    },
    "pais": {
      "type": "object",
      "properties": {
        "codigo": {
          "type": "integer"
        },
        "nome": {
          "type": "string"
        }
      },
      "required": [
        "codigo",
        "nome"
      ]
    },
    "dataDeEntradaPais": {
      "type": "string"
    }
  },
  "required": [
    "individuo",
    "datadeNascimento",
    "nascimentoAcuracia",
    "nascimentoSegmento",
    "nascimentoPluralidade",
    "nascimentoOrdem",
    "obito",
    "obitoAcuracia",
    "obitoFonte",
    "sexo",
    "mae",
    "pai",
    "situacaoFamiliar",
    "raca",
    "comentario",
    "nacionalidade",
    "municipio",
    "estado",
    "pais",
    "dataDeEntradaPais"
  ]
}

=== saulocalixto/mf-2018/aula-7/dto/src/test/resources/arquivosJson/dadoDemografico.json
{"individuo":{"id":"0239skdlfj2029"},"datadeNascimento":"Nov 18, 2018 2:09:15 PM","nascimentoAcuracia":"Nov 18, 2018 2:09:15 PM","nascimentoSegmento":{"codigo":"100","descricao":"descricao"},"nascimentoPluralidade":{"codigo":100,"descricao":"descricao"},"nascimentoOrdem":{"codigo":100,"descricao":"descricao"},"obito":"Nov 18, 2018 2:09:15 PM","obitoAcuracia":"Obito Acurácia","obitoFonte":{"codigo":100,"descricao":"descricao"},"sexo":{"codigo":100,"alternativo":"alternativa","descricao":"descricao"},"mae":"Mãe","pai":"Pai","situacaoFamiliar":{"codigo":100,"descricao":"descricao"},"raca":{"codigo":100,"descricao":"descricao"},"comentario":"comentário","nacionalidade":{"codigo":100,"descricao":"descricao"},"municipio":{"codigo":"3571","estado":"Goiás","municipio":"Goiânia"},"estado":{"codigo":"562","nome":"Goiás"},"pais":{"codigo":500,"nome":"Brasil"},"dataDeEntradaPais":"Nov 18, 2018 2:09:15 PM"}
